name: Push to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on branch push
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{secrets.EC2_SSH_KEY}}
        run: |
          echo "$EC2_SSH_KEY" > keyfile
          chmod 600 keyfile
          ssh -t -i kyefile ubuntu@"$HOST_IP" "echo 'Hello, world! > hello'"
