name: Continuous Intergration Workflow

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./server

jobs:

  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        name: 'Checkout repository'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run Tests'
        run: npm run test

  format:
    name: 'Run check format'
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run Formatter'
      run: npm run prettier-check
