name: Create a comment on a new issues

on:
  issues:
    types:
      - opened
  workflow_dispatch:

jobs:
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api -X POST \
          http:api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='
          Comment but from API call not action
          '
          env:
            GITHUB_TOKEN: ${{ secrets.FUCK }}
            ORGANIZATION: ${{ github.event.organisation.login }}
            REPOSITORY: ${{ github.event.repository.name }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
