name: Continuous Intergration Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/src
        shell: bash

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: 'Prettify code'
        uses: creyD/prettier_action@v4.3
        with:
         prettier_options: --check
